os: osx
osx_image: xcode11.4.1
language: swift
script: xcodebuild clean build test -workspace WeatherApp.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.4,name=iPhone 11 Pro" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO


after_success:
  - bash <(curl -s https://codecov.io/bash)
